package report

import (
	"fmt"
	"io"
	"strings"

	"github.com/nashory/agent-cockpit/internal/usage"
)

// SVG writes a shareable "receipt card" summarizing usage as a self-contained
// SVG image: headline totals plus the top models. Costs are labeled estimated
// (a leading ~) since they are derived from token counts, not recorded.
func SVG(w io.Writer, title string, events []usage.Event, opts Options) {
	t := usage.SummarizeWith(events, opts.Pricing)
	models := usage.GroupByWith(events, opts.Pricing, func(e usage.Event) string { return e.Model })
	if len(models) > 5 {
		models = models[:5]
	}
	cur := opts.currency()

	const width = 820
	const headerH = 172
	const rowH = 34
	height := headerH + 24 + len(models)*rowH + 44

	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	p(`<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d" font-family="ui-monospace,SFMono-Regular,Menlo,monospace">`, width, height, width, height)
	p(`<rect width="%d" height="%d" rx="14" fill="#0b0f14"/>`, width, height)
	p(`<rect x="1" y="1" width="%d" height="%d" rx="13" fill="none" stroke="#1c2530"/>`, width-2, height-2)
	p(`<text x="32" y="52" fill="#36d0e0" font-size="26" font-weight="700">&#9992; agent-cockpit</text>`)
	p(`<text x="32" y="80" fill="#7d8895" font-size="14">%s</text>`, esc(title))

	stats := []struct{ label, val, color string }{
		{"TOKENS", formatInt(t.Total), "#36d0e0"},
		{"COST", fmt.Sprintf("~%.2f %s", t.CostUSD, cur), "#3ad07a"},
		{"EVENTS", formatInt(int64(t.Events)), "#e6edf3"},
		{"CACHE", formatInt(t.CacheRead + t.CacheCreate), "#7d8895"},
	}
	cardW := (width - 64 - 3*12) / 4
	for i, s := range stats {
		x := 32 + i*(cardW+12)
		p(`<rect x="%d" y="100" width="%d" height="56" rx="8" fill="#11171f"/>`, x, cardW)
		p(`<text x="%d" y="122" fill="#7d8895" font-size="11">%s</text>`, x+12, s.label)
		p(`<text x="%d" y="144" fill="%s" font-size="18" font-weight="700">%s</text>`, x+12, s.color, esc(s.val))
	}

	yTop := headerH
	p(`<text x="32" y="%d" fill="#7d8895" font-size="12" letter-spacing="1">TOP MODELS</text>`, yTop)
	var maxTok int64 = 1
	if len(models) > 0 && models[0].Totals.Total > 0 {
		maxTok = models[0].Totals.Total
	}
	const barX = 210
	barMax := width - barX - 210
	for i, m := range models {
		y := yTop + 22 + i*rowH
		bw := int(float64(m.Totals.Total) / float64(maxTok) * float64(barMax))
		if bw < 2 {
			bw = 2
		}
		p(`<text x="32" y="%d" fill="#e6edf3" font-size="13">%s</text>`, y+14, esc(short(m.Key)))
		p(`<rect x="%d" y="%d" width="%d" height="16" rx="3" fill="#1c2530"/>`, barX, y+2, barMax)
		p(`<rect x="%d" y="%d" width="%d" height="16" rx="3" fill="#36d0e0"/>`, barX, y+2, bw)
		p(`<text x="%d" y="%d" fill="#7d8895" font-size="12" text-anchor="end">%s &#183; ~%.2f %s</text>`,
			width-32, y+14, formatInt(m.Totals.Total), m.Totals.CostUSD, cur)
	}

	p(`<text x="32" y="%d" fill="#5a6675" font-size="11">Costs are estimated from token counts (LiteLLM pricing). Generated by agent-cockpit.</text>`, height-20)
	p(`</svg>`)
	_, _ = io.WriteString(w, b.String())
}

func esc(s string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;").Replace(s)
}
